import { notFound } from 'next/navigation'
import { ArrowLeft, ArrowUpRight } from 'lucide-react'
import Link from 'next/link'
import { products, getProductBySlug } from '@/lib/products'
import { SiteChrome } from '@/components/site-header'
import { CartDrawer } from '@/components/cart-drawer'
import { AddToCart } from '@/components/add-to-cart'
import { formatPrice, badgeLabel } from '@/lib/utils'
export function generateStaticParams() { return products.map(p => ({ slug: p.slug })) }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const p = getProductBySlug(slug); if (!p) notFound(); return <SiteChrome><CartDrawer/><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8 lg:py-16"><Link href="/#boutique" className="mb-10 flex items-center gap-2 text-xs uppercase tracking-widest text-muted-foreground"><ArrowLeft size={14}/> Retour à la boutique</Link><div className="grid gap-10 lg:grid-cols-2 lg:gap-20"><div className="relative aspect-[4/5] bg-secondary"><img src={p.image} alt={p.name} className="absolute inset-0 h-full w-full object-cover"/></div><div className="flex flex-col justify-center"><p className="eyebrow">{p.category}{p.badge && ` · ${badgeLabel(p.badge)}`}</p><h1 className="mt-4 max-w-lg text-5xl font-semibold leading-none tracking-tight md:text-6xl">{p.name}</h1><div className="mt-6 flex items-center gap-3"><span className="text-lg">{formatPrice(p.price)}</span>{p.oldPrice && <span className="text-sm text-muted-foreground line-through">{formatPrice(p.oldPrice)}</span>}</div><p className="mt-8 max-w-md text-sm leading-7 text-muted-foreground">{p.longDescription}</p><p className="mt-6 text-xs uppercase tracking-widest">{p.stock > 0 ? `${p.stock} pièces disponibles` : 'Rupture de stock'}</p><div className="mt-8 max-w-sm"><AddToCart product={p}/></div><div className="mt-10 border-t border-border pt-6 text-sm leading-7 text-muted-foreground">{p.details}</div><a href="https://wa.me/2250710504007" className="mt-8 flex w-fit items-center gap-2 text-xs uppercase tracking-widest underline underline-offset-8">Une question ? Écrire sur WhatsApp <ArrowUpRight size={14}/></a></div></div></main></SiteChrome> }
